# -*- coding: utf-8 -*-
"""Homework6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpPUNawnHT7Ydo3lDYE4UUrLs8lPMfcO
"""

#Problem 1

from collections import deque
import copy

def DFS_recursive(grid: list[list[str]]) -> int:
    rows, cols = len(grid), len(grid[0])
    count = 0

    def visit(r, c):
        if 0 <= r < rows and 0 <= c < cols and grid[r][c] == '1':
            grid[r][c] = '0'  # Marked as visited
            for dr, dc in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
                visit(r + dr, c + dc)

    for r in range(rows):
        for c in range(cols):
            if grid[r][c] == '1':
                count += 1
                visit(r, c)
    return count

def DFS_iterative(grid: list[list[str]]) -> int:
    rows, cols = len(grid), len(grid[0])
    count = 0

    for r in range(rows):
        for c in range(cols):
            if grid[r][c] == '1':
                count += 1
                stack = [(r, c)]
                grid[r][c] = '0'
                while stack:
                    curr_r, curr_c = stack.pop()
                    for dr, dc in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
                        nr, nc = curr_r + dr, curr_c + dc
                        if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] == '1':
                            grid[nr][nc] = '0'
                            stack.append((nr, nc))
    return count

def BFS(grid: list[list[str]]) -> int:
    rows, cols = len(grid), len(grid[0])
    count = 0

    for r in range(rows):
        for c in range(cols):
            if grid[r][c] == '1':
                count += 1
                queue = deque([(r, c)])
                grid[r][c] = '0'
                while queue:
                    curr_r, curr_c = queue.popleft()
                    for dr, dc in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
                        nr, nc = curr_r + dr, curr_c + dc
                        if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] == '1':
                            grid[nr][nc] = '0'
                            queue.append((nr, nc))
    return count

def run_tests():
    grid_template = [
        ['1', '1', '0', '0', '0'],
        ['1', '1', '0', '0', '0'],
        ['0', '0', '1', '0', '0'],
        ['0', '0', '0', '1', '1']
    ]

    methods = [
        ("Recursive DFS", DFS_recursive),
        ("Iterative DFS", DFS_iterative),
        ("BFS", BFS)
    ]


    for name, func in methods:
        test_grid = copy.deepcopy(grid_template)
        print(f"{name}: {func(test_grid)} islands found.")

run_tests()